### ISSUE TITLE
Update documents

### ISSUE THREAD

**Issue by kevinnguyen20** [kevinnguyen20/data-aggregation-in-distributed-networks#9]
Complete the following files:
- CONTRIBUTING
- LICENSE
- SECURITY

**Comment by gogokotsev00** [comment]
I am not sure that we need such files

**Comment by kevinnguyen20** [comment]
I think at least we should have a LICENSE file

**Comment by gogokotsev00** [comment]
We are not using licensed products, why would we need this file?
